FIX

diff --git a/.github/workflows/upstream.yml b/.github/workflows/upstream.yml
--- a/.github/workflows/upstream.yml
+++ b/.github/workflows/upstream.yml
@@ -35,7 +35,7 @@ jobs:
 
     - uses: de-vri-es/setup-git-credentials@v2
       with:
-        credentials: https://kiddin9:${{ secrets.TOKEN_KIDDIN9 }}@github.com/
+        credentials: https://Dronnis:${{ secrets.TOKEN_KIDDIN9 }}@github.com/
     
     - name: Set git identity
       run : |
@@ -50,12 +50,16 @@ jobs:
         git rm -r --cache * >/dev/null 2>&1 &
         rm -rf `find ./* -maxdepth 0 -type d ! -name ".github/diy"` >/dev/null 2>&1
         function git_clone() {
-          git clone --depth 1 $1 $2
-          if [ "$?" != 0 ]; then
-            echo "error on $1"
-            pid="$( ps -q $$ )"
-            kill $pid
+          local url="$1"
+          local target="${2:-$(basename "$1" .git)}"  # ← если $2 не задан, берём имя репо из URL
+          
+          echo "🔄 Cloning: $url → $target" >&2
+          
+          if ! timeout 300 git clone --depth 1 --quiet "$url" "$target" 2>&1; then
+            echo "❌ ERROR: Failed to clone $url" >&2
+            return 1
           fi
+          return 0
         }
         function git_sparse_clone() {
         trap 'rm -rf "$tmpdir"' EXIT
@@ -173,7 +177,7 @@ jobs:
         git_clone https://github.com/KFERMercer/luci-app-tcpdump
         git_clone https://github.com/ykxVK8yL5L/pikpak-webdav pikpak && mv -n pikpak/openwrt/* ./;rm -rf pikpak
         git_clone https://github.com/jjm2473/openwrt-apps && rm -rf openwrt-apps/{luci-app-cpufreq,luci-app-ota,homebox,luci-alias.mk} && sed -i "s/luci-alias.mk/..\/luci.mk/" openwrt-apps/*/Makefile && mvdir openwrt-apps
-        git_clone https://github.com/nikkinikki-org/OpenWrt-nikki && mv -f OpenWrt-nikki/{luci-app-nikki,nikki,mihomo*} ./;rm -rf OpenWrt-nikki
+        git_clone https://github.com/nikkinikki-org/OpenWrt-nikki && mv -f OpenWrt-nikki/{luci-app-nikki,nikki} ./;rm -rf OpenWrt-nikki
         git_clone https://github.com/nikkinikki-org/OpenWrt-momo && mv -f OpenWrt-momo/{luci-app-momo,momo} ./;rm -rf OpenWrt-momo
         ) &
         (
@@ -343,6 +347,8 @@ jobs:
         net/vpnbypass net/vpn-policy-routing utils/qfirehose
         git_sparse_clone master "https://github.com/lunatickochiya/Matrix-Action-Openwrt" package/kochiya/brlaser package/kochiya/luci-app-banmac-ipt package/kochiya/luci-app-banmac-nft package/kochiya/luci-app-nvr package/kochiya/luci-app-openvpn-server package/kochiya/luci-app-openvpn-server-client
         git_sparse_clone main https://github.com/sbwml/openwrt_pkgs luci-app-socat
+        ) & (
+        git_sparse_clone zap1 "https://github.com/remittor/zapret-openwrt"  luci-app-zapret zapret
         ) &
         (
         git_sparse_clone master "https://github.com/xiaoqingfengATGH/feeds-xiaoqingfeng" homeredirect luci-app-homeredirect
